/*
 * generated by Xtext
 */
package com.dubture.editor.sass.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.dubture.editor.sass.ui.internal.SassActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SassExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SassActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SassActivator.getInstance().getInjector(SassActivator.COM_DUBTURE_EDITOR_SASS_SASS);
	}
	
}
