/*
* generated by Xtext
*/
package com.dubture.editor.sass;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SassUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.dubture.editor.sass.ui.internal.SassActivator.getInstance().getInjector("com.dubture.editor.sass.Sass");
	}
	
}
