/*
 * generated by Xtext
 */
package com.dubture.editor.sass;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SassRuntimeModule extends com.dubture.editor.sass.AbstractSassRuntimeModule {

}
