/*
* generated by Xtext
*/
package com.dubture.editor.sass;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SassStandaloneSetup extends SassStandaloneSetupGenerated{

	public static void doSetup() {
		new SassStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

