/**
 * generated by Xtext
 */
package com.dubture.editor.sass.validation;

import com.dubture.editor.sass.validation.AbstractSassValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SassValidator extends AbstractSassValidator {
}
