/*
 * generated by Xtext
 */
package com.dubture.editor.sass.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SassUiModule extends com.dubture.editor.sass.ui.AbstractSassUiModule {
	public SassUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
