/*
 * generated by Xtext
 */
package com.dubture.editor.sass.ui.contentassist

import com.dubture.editor.sass.ui.contentassist.AbstractSassProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class SassProposalProvider extends AbstractSassProposalProvider {
}
